modLoader="javafml" #mandatory
loaderVersion="[31,)" #mandatory
issueTrackerURL="https://github.com/bageldotjpg/BuzzierBees/issues" #optional

[[mods]] #mandatory
modId="buzzierbees" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Buzzier Bees" #mandatory
displayURL="https://discord.gg/zVBFsXp" #optional
logoFile="logo.png" #optional
credits="Bratistolf" #optional
authors="bageldotjpg, Five, and Farcr" #optional

description='''
Buzzier Bees expands on the content introduced in 1.15. 
Main features include wax, crystallized honey, and candles, and much more!
Grizzly Bears, Black Bears, and Bumblebees will come soon!
'''

[[dependencies.buzzierbees]]
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[31.1.85,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.buzzierbees]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"

[[dependencies.buzzierbees]]
    modId="abnormals_core"
    mandatory=true
    versionRange="[1.0.5,)"
    ordering="AFTER"
    side="BOTH"
