modLoader="javafml" #mandatory
loaderVersion="[29,)" #mandatory
issueTrackerURL="https://github.com/bageldotjpg/BuzzierBees/issues" #optional

[[mods]] #mandatory
modId="buzzierbees" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Buzzier Bees" #mandatory
displayURL="https://discord.gg/zVBFsXp" #optional
logoFile="buzzierbees" #optional
credits="Five & Farcr, and the other members of my team for Art" #optional
authors="bageldotjpg & Bratistolf" #optional

description='''
Buzzier Bees expands on the content introduced in 1.15. 
Main features include wax, crystallized honey, and candles, and much more!
Beekeepers, Brown Bears, and Butterflies will come soon!
'''

# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.buzzierbees]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[29,)" #mandatory
    ordering="NONE"
    side="BOTH"
